---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: idock.daumkakao.io/techcampus/backend
          env:
            - name: TZ
              value: Asia/Seoul
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mariadb://mariadb:3306/kakao
          resources:
            requests:
              memory: 1Gi
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
    - port: 8080
